variables:
  # To optimize CI/CD time
  GIT_DEPTH: 10
  # To avoid SSL certificate verification error when cloning private repositories
  GIT_SSL_NO_VERIFY: 1

default:
  image:
    name: theohbrothers/docker-ansible:v2.10.7-alpine-3.13
    pull_policy: if-not-present
  tags:
    - docker

stages:
  - caserver
  - vpnserver
  - clients
  - backend

.setup_ansible:
  before_script:
    - mkdir -p /etc/ansible/
    - cp -f "$ANSIBLE_CFG" /etc/ansible/ansible.cfg

create-certificates:
  stage: caserver
  extends: .setup_ansible
  script:
    - ansible-playbook -i $ANSIBLE_INVENTORY --private-key "$SSH_PRIVATE_KEY" playbooks/create_certificates.yml
  when: manual

config-vpnserver:
  stage: vpnserver
  extends: .setup_ansible
  script:
    - ansible-playbook -i $ANSIBLE_INVENTORY --private-key "$SSH_PRIVATE_KEY" playbooks/config_vpnserver.yml
  when: manual

create-clients:
  stage: clients
  extends: .setup_ansible
  script:
    - mkdir -p clients
    - pwd
    - ls -la
    - ansible-playbook -i $ANSIBLE_INVENTORY --private-key "$SSH_PRIVATE_KEY" playbooks/create_clients.yml
  when: manual
  artifacts:
    paths:
      - clients/

config-backend:
  stage: backend
  extends: .setup_ansible
  script:
    - ansible-playbook -i $ANSIBLE_INVENTORY --private-key "$SSH_PRIVATE_KEY" playbooks/config_backend.yml
  when: manual
