---
- name: Check if docker is installed
  stat:
    path: /usr/bin/docker
  register: docker_installed

- block:
    - name: Install packages
      apt:
        name: ["ca-certificates", "curl", "gnupg"]
        state: latest
        update_cache: true

    - name: Create docker apt keyrings directory
      file:
        path: /etc/apt/keyrings
        state: directory
        mode: 0755
        force: false

    - name: Add Docker's official GPG key
      shell: |
        curl -fsSL https://download.docker.com/linux/debian/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
      args:
        creates: /etc/apt/keyrings/docker.gpg

    - name: Get architecture
      command: dpkg --print-architecture
      register: architecture

    - name: Get version code name
      command: lsb_release -cs
      register: version

    - name: Add Docker apt repository
      apt_repository:
        # repo: deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/debian bullseye stable
        repo: deb [arch={{ architecture.stdout }} signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/debian {{ version.stdout }} stable
        state: present

    - name: Update apt and install docker-ce
      apt:
        name: docker-ce
        state: latest
        update_cache: true

    - name: Install docker-compose plugin
      apt:
        name: docker-compose-plugin
        state: latest
  when: docker_installed.stat.exists == false
