version: '3'

services:
  nginx-cve-2019-11043:
    container_name: nginx-cve-2019-11043
    image: nginx:1
    volumes:
      - ./www:/usr/share/nginx/html
      - ./default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php-cve-2019-11043
    restart: unless-stopped

  php-cve-2019-11043:
    container_name: php-cve-2019-11043
    image: php:7.2.10-fpm
    volumes:
      - ./www:/var/www/html
    restart: unless-stopped