---
# Configure and start the VPN server
- hosts: vpnserver
  roles:
    - vpnserver
    - caserver # This role can be removed if the certificates are copied from a different machine
  become: true
  tasks:
    - name: Copy server certificates and keys
      copy:
        src: "{{ item }}"
        dest: "{{ vpn_config_dir }}"
        owner: root
        group: root
        mode: 0600
        remote_src: true
      with_items:
        - "{{ easyrsa_dir }}/pki/ca.crt"
        - "{{ easyrsa_dir }}/pki/dh.pem"
        - "{{ easyrsa_dir }}/pki/issued/server.crt"
        - "{{ easyrsa_dir }}/pki/private/server.key"
        - "{{ easyrsa_dir }}/pki/ta.key"

    - name: Install packages
      apt:
        name: ["openvpn", "ufw"]
        state: latest
        update_cache: true

    - name: Configure openvpn server
      template:
        src: server.conf.j2
        dest: "{{ vpn_config_dir }}/server.conf"
        owner: root
        group: root
        mode: 0600

    - name: Reset ufw
      ufw:
        state: reset

    - name: Allow OpenVPN udp traffic
      ufw:
        rule: allow
        port: "1194"
        proto: udp

    - name: Add ufw rule to allow ssh traffic
      ufw:
        rule: allow
        port: "22"
        proto: tcp

    - name: Allow IPv4 forwarding
      sysctl:
        name: net.ipv4.ip_forward
        value: "1"
        state: present
        reload: yes

    - name: Insert port forwarding rule for ufw
      lineinfile:
        dest: /etc/ufw/before.rules
        line: "{{ item }}"
      with_items:
        - "*nat"
        - ":POSTROUTING ACCEPT [0:0]"
        - "-A POSTROUTING -s {{ vpn_network }}/{{ vpn_netcidr }} -o {{ private_interface }} -j MASQUERADE \nCOMMIT"

    - name: Allow clients traffic to port 2222
      ufw:
        rule: allow
        from_ip: "{{ vpn_network }}/{{ vpn_netcidr }}"
        to_ip: "{{ private_network }}/{{ private_netcidr }}"
        to_port: "2222"
        proto: tcp
        route: true

    - name: Enable ufw
      ufw:
        state: enabled

    - name: Start openvpn server
      service:
        name: openvpn-server@server
        state: started
        enabled: true
