---
- hosts: backend
  become: true
  roles:
    - docker_installer
  tasks:
    - name: Copy pentest-lab directory
      copy:
        src: "pentest-lab"
        dest: "/root"
        owner: root
        group: root
        mode: 0755

    - name: Run docker-compose
      command: "docker compose up --build --remove-orphans -d"
      args:
        chdir: "/root/pentest-lab"
