---
# Generate certificates for the VPN server
# This playbook can be run on the VPN server itself or on a different
# machine and then the certificates can be copied to the VPN server.
# https://community.openvpn.net/openvpn/wiki/EasyRSA3-OpenVPN-Howto
- hosts: vpnserver
  roles:
    - caserver
  environment:
    EASYRSA_BATCH: "true"
  become: true
  tasks:
    - name: Install dependencies
      apt:
        name: ["curl"]
        state: latest
        update_cache: true

    - name: Install the latest version of easyrsa
      shell: |
        easyrsa_version=$(curl --silent "https://api.github.com/repos/OpenVPN/easy-rsa/releases/latest" | grep '"tag_name":' | sed -E 's/.*"v([^"]+)".*/\1/')
        easyrsa_url="https://github.com/OpenVPN/easy-rsa/releases/download/v${easyrsa_version}/EasyRSA-${easyrsa_version}.tgz"
        curl -so /tmp/easyrsa.tgz -L "$easyrsa_url"
        tar -xzf /tmp/easyrsa.tgz -C {{ easyrsa_install_path }}
        mv {{ easyrsa_install_path }}/EasyRSA-${easyrsa_version} {{ easyrsa_install_path }}/EasyRSA
      args:
        creates: "{{ easyrsa_bin }}"

    - name: Initialize PKI
      command: "{{ easyrsa_bin }} init-pki"
      args:
        chdir: "{{ easyrsa_dir }}"
        creates: "{{ easyrsa_dir }}/pki"

    - name: Build CA
      command: "{{ easyrsa_bin }} build-ca nopass"
      args:
        chdir: "{{ easyrsa_dir }}"
        creates: "{{ easyrsa_dir }}/pki/private/ca.key"

    - name: Generate server certificate
      command: "{{ easyrsa_bin }} build-server-full server nopass"
      args:
        chdir: "{{ easyrsa_dir }}"
        creates: "{{ easyrsa_dir }}/pki/issued/server.crt"

    - name: Generate DH params
      command: "{{ easyrsa_bin }} gen-dh"
      args:
        chdir: "{{ easyrsa_dir }}"
        creates: "{{ easyrsa_dir }}/pki/dh.pem"

    - name: Install openvpn
      apt:
        name: ["openvpn"]
        state: latest

    - name: Generate TLS-auth key
      shell: |
        openvpn --genkey --secret {{ easyrsa_dir }}/pki/ta.key
      args:
        creates: "{{ easyrsa_dir }}/pki/ta.key"
