---
# https://github.com/BastiPaeltz/ansible-openvpn
- hosts: vpnserver
  roles:
    - caserver
  become: true
  tasks:
    - name: Generate client certificates
      environment:
        EASYRSA_BATCH: "true"
      command: "{{ easyrsa_bin }} build-client-full {{ item }} nopass"
      args:
        chdir: "{{ easyrsa_dir }}"
        creates: "{{ easyrsa_dir }}/pki/issued/{{ item }}.crt"
      loop: "{{ vpn_clients }}"

    - name: Register CA certificate
      command: "cat {{ easyrsa_dir }}/pki/ca.crt"
      no_log: true
      register: ca_cert
      changed_when: false

    - name: Register tls-auth key
      command: "cat {{ easyrsa_dir }}/pki/ta.key"
      no_log: true
      register: ta_key
      changed_when: false

    - name: Register client certificates
      command: "cat {{ easyrsa_dir }}/pki/issued/{{ item }}.crt"
      with_items: "{{ vpn_clients }}"
      no_log: true
      register: client_certs
      changed_when: false

    - name: Register client keys
      command: "cat {{ easyrsa_dir }}/pki/private/{{ item }}.key"
      with_items: "{{ vpn_clients }}"
      no_log: true
      register: client_keys
      changed_when: false

    - name: Generate client config files
      template:
        src: "client.ovpn.j2"
        dest: "{{ client_config_dir }}/{{ item[0] }}.ovpn"
        owner: root
        group: root
        mode: 0400
        force: false
      no_log: true
      with_together:
        - "{{ vpn_clients }}"
        - "{{ client_certs.results }}"
        - "{{ client_keys.results }}"

    - name: Download client config files
      fetch:
        src: "{{ client_config_dir }}/{{ item }}.ovpn"
        dest: "{{ lookup('env', 'PWD') }}/clients/"
        flat: yes
      with_items: "{{ vpn_clients }}"
